import Infrastructure

public typealias CompositeRuntimeEventRepositoryError = Infrastructure.CompositeRuntimeEventRepositoryError
public typealias CompositeRuntimeEventRepository = Infrastructure.CompositeRuntimeEventRepository
