import Infrastructure

public typealias RuntimeStorageCapacityValues = Infrastructure.RuntimeStorageCapacityValues
public typealias SystemRuntimeStorageUsageProvider = Infrastructure.SystemRuntimeStorageUsageProvider
