import Domain

public typealias RuntimeFreshInstallPreflightInput = Domain.RuntimeFreshInstallPreflightInput
public typealias RuntimeFreshInstallPreflightPolicy = Domain.RuntimeFreshInstallPreflightPolicy
