// Generated from release-dev.json by make vm-version-source.
// Do not edit this file directly.

import Contracts

public extension Constants {
    static let launcherVersion = "0.2.0"
    static let launcherChannel = UpdateBundleChannel(
        rawValue: "dev"
    )
}
