// Generated from release-dev.json by make devtools/release-contract.
// Do not edit this file directly.

import Contracts

public extension Constants {
    static let launcherVersion = "0.2.1"
    static let launcherChannel = UpdateBundleChannel(
        rawValue: "dev"
    )
}
