import Application

public typealias RuntimeTemporaryDirectoryProviding = Application.RuntimeTemporaryDirectoryProviding
public typealias RuntimeFileReading = Application.RuntimeFileReading
public typealias RuntimeFilePartialReading = Application.RuntimeFilePartialReading
public typealias RuntimeFileWriting = Application.RuntimeFileWriting
public typealias RuntimeDirectoryListing = Application.RuntimeDirectoryListing
public typealias RuntimeDirectoryMeasuring = Application.RuntimeDirectoryMeasuring
public typealias RuntimeDiskUsageProviding = Application.RuntimeDiskUsageProviding
public typealias RuntimeFileSystemAttributes = Application.RuntimeFileSystemAttributes
public typealias RuntimeFileStore = Application.RuntimeFileStore
