import Interfaces

public typealias RuntimeControlHTTPMethod = Interfaces.RuntimeControlHTTPMethod
public typealias RuntimeControlAPIScope = Interfaces.RuntimeControlAPIScope
public typealias RuntimeControlAPIClientAccess = Interfaces.RuntimeControlAPIClientAccess
public typealias RuntimeControlAPIStreamCapability = Interfaces.RuntimeControlAPIStreamCapability
public typealias RuntimeControlAPIErrorCode = Interfaces.RuntimeControlAPIErrorCode
public typealias RuntimeControlAPIRoute = Interfaces.RuntimeControlAPIRoute
public typealias RuntimeControlAPIEndpoint = Interfaces.RuntimeControlAPIEndpoint
public typealias RuntimeControlFileReferenceKind = Interfaces.RuntimeControlFileReferenceKind
public typealias RuntimeControlFileReference = Interfaces.RuntimeControlFileReference
public typealias RuntimeControlErrorResponse = Interfaces.RuntimeControlErrorResponse
public typealias RuntimeControlErrorResponseEncoder = Interfaces.RuntimeControlErrorResponseEncoder
public typealias RuntimeControlCommandResponse = Interfaces.RuntimeControlCommandResponse
public typealias RuntimeApplySettingsRequest = Interfaces.RuntimeApplySettingsRequest
public typealias RuntimeRepairProxyRequest = Interfaces.RuntimeRepairProxyRequest
public typealias RuntimeUninstallRequest = Interfaces.RuntimeUninstallRequest
public typealias RuntimeLogTextRequest = Interfaces.RuntimeLogTextRequest
public typealias RuntimeLogTextResponse = Interfaces.RuntimeLogTextResponse
public typealias RuntimeUpdateBundleRequest = Interfaces.RuntimeUpdateBundleRequest
public typealias RuntimeUpdateBundleSummaryResponse = Interfaces.RuntimeUpdateBundleSummaryResponse
public typealias RuntimeBackupRequest = Interfaces.RuntimeBackupRequest
public typealias RuntimeExportLogsRequest = Interfaces.RuntimeExportLogsRequest

public typealias RuntimeControlHTTPStatus = Interfaces.RuntimeControlHTTPStatus
public typealias RuntimeControlHTTPRequest = Interfaces.RuntimeControlHTTPRequest
public typealias RuntimeControlHTTPResponse = Interfaces.RuntimeControlHTTPResponse
public typealias RuntimeControlHTTPStreamResponse = Interfaces.RuntimeControlHTTPStreamResponse
public typealias RuntimeControlHTTPRouteResult = Interfaces.RuntimeControlHTTPRouteResult
public typealias RuntimeControlAPIStreamConfiguration = Interfaces.RuntimeControlAPIStreamConfiguration
public typealias RuntimeControlAPIReadHandler = Interfaces.RuntimeControlAPIReadHandler
public typealias RuntimeControlAPIRouter = Interfaces.RuntimeControlAPIRouter
public typealias RuntimeControlServerSentEventCodec = Interfaces.RuntimeControlServerSentEventCodec
public typealias RuntimeControlServerSentEventEncodingError = Interfaces.RuntimeControlServerSentEventEncodingError
public typealias RuntimeControlServerSentEvent = Interfaces.RuntimeControlServerSentEvent
public typealias RuntimeControlAPIAuthorization = Interfaces.RuntimeControlAPIAuthorization
public typealias RuntimeControlHTTPQueryError = Interfaces.RuntimeControlHTTPQueryError
public typealias RuntimeControlClientAPIReadHandler = Interfaces.RuntimeControlClientAPIReadHandler
public typealias RuntimeControlAPIReadHandlerError = Interfaces.RuntimeControlAPIReadHandlerError

public typealias RuntimeControlHTTPWireCodecError = Interfaces.RuntimeControlHTTPWireCodecError
public typealias RuntimeControlHTTPWireCodec = Interfaces.RuntimeControlHTTPWireCodec
public typealias RuntimeControlStaticFileResponder = Interfaces.RuntimeControlStaticFileResponder
public typealias RuntimeControlLocalHTTPServerError = Interfaces.RuntimeControlLocalHTTPServerError
public typealias RuntimeControlLocalHTTPServerState = Interfaces.RuntimeControlLocalHTTPServerState
public typealias RuntimeControlLocalHTTPServerConfiguration = Interfaces.RuntimeControlLocalHTTPServerConfiguration
public typealias RuntimeControlLocalHTTPServer = Interfaces.RuntimeControlLocalHTTPServer

public typealias RuntimeTestKitAPIRouter = Interfaces.RuntimeTestKitAPIRouter
public typealias RuntimeTestKitAPIEndpoint = Interfaces.RuntimeTestKitAPIEndpoint
public typealias RuntimeTestKitStopRequest = Interfaces.RuntimeTestKitStopRequest
public typealias RuntimeTestKitDeleteRequest = Interfaces.RuntimeTestKitDeleteRequest
public typealias RuntimeTestKitRestartRequest = Interfaces.RuntimeTestKitRestartRequest
public typealias RuntimeTestKitRecorderDeletionRequest = Interfaces.RuntimeTestKitRecorderDeletionRequest
public typealias RuntimeControlDevConsoleDocument = Interfaces.RuntimeControlDevConsoleDocument
