import Errors

public extension AppConstants {
    enum Actions {
        public static let healthCheck = "Health Check"
        public static let open = "Open"
        public static let openVitalFilesDirectory = "Open Vital Files Directory"
        public static let refresh = "Refresh"
        public static let repairProxy = "Repair Proxy"
        public static let repairProxyPort = "Repair Proxy Port"
        public static let repairDatastore = "Repair Redis Datastore"
        public static let repairVMDisk = "Repair VM Disk"
        public static let repairRuntimeServices = "Repair Runtime"
        public static let uninstall = "Uninstall"
        public static let standardUninstall = "Uninstall..."
        public static let cleanUninstall = "Clean Uninstall..."
        public static let vmRootfsUpdate = "VM/rootfs Update"
        public static let applySettings = "Apply"
        public static let chooseDirectory = "Choose..."
        public static let chooseBundle = "Choose Bundle"
        public static let verifyBundle = "Verify"
        public static let applyBundle = "Apply Bundle"
        public static let rollback = "Rollback"
        public static let createBackup = "Create VitalServer Backup"
        public static let importBackups = "Import Backups"
        public static let restoreBackup = "Restore VitalServer Backup"
        public static let createRedisBackup = "Create Redis-only Backup"
        public static let restoreRedisBackup = "Restore Redis-only Backup"
        public static let deleteBackup = "Delete Backup"
        public static let deleteUpdateBackup = "Delete Update Backup"
        public static let deleteVitalServerBackup = "Delete VitalServer Backup"
        public static let checkRecorders = "Check Recorders"
        public static let openBackups = "Open Backups"
        public static let openLogs = "Open Logs"
        public static let exportLogs = "Export Logs"
        public static let start = "Start"
        public static let pause = "Pause"
        public static let resume = "Resume"
        public static let stop = "Stop"
        public static let restart = "Restart"
        public static let create = "Create"
        public static let delete = "Delete"
        public static let deleteVRecorder = "Delete VRecorder"
        public static let uploadVitalFiles = "Upload .vital Files"
        public static let reset = "Reset"
        public static let startRuntimeServices = "Start Runtime Services"
        public static let stopRuntimeServices = "Stop Runtime Services"
        public static let restartVMRuntime = "Restart VM Runtime"
        public static let startUpdate = "Start Update"
        public static let startRollback = "Start Rollback"
        public static let ok = "OK"
        public static let cancel = "Cancel"
        public static let createFolder = "Create Folder"
        public static let continueAction = "Continue"
        public static let back = "Back"
        public static let install = "Install"
    }
}
