import Foundation
import Contracts
import Errors

public extension AppConstants {
    enum Labels {
        public static let sectionStatus = "Status"
        public static let sectionRecorders = "Recorders"
        public static let sectionBeds = "Beds"
        public static let sectionSettings = "Settings"
        public static let sectionUpdate = "Update"
        public static let sectionObservability = "Observability"
        public static let sectionTest = "Test"
        public static let sectionAdvanced = "Advanced"
        public static let sectionInfo = "About"
        public static let sectionDangerZone = "Danger Zone"
        public static let sectionLog = "Logs"
        public static let sectionMore = "More"
        public static let runtime = "Runtime"
        public static let runtimeDetails = "Runtime details"
        public static let runtimeState = "Runtime state"
        public static let statusDocument = "Status document"
        public static let guestRuntimeState = "Guest runtime state"
        public static let vitalServerURL = "VitalServer URL"
        public static let runtimeControlPWA = "Remote Console"
        public static let dataDirectory = "Data directory"
        public static let actionNeeded = "Action needed"
        public static let recommendedAction = "Recommended action"
        public static let overallHealth = "Overall health"
        public static let resourceUsage = "Resource usage"
        public static let cpuUsage = "CPU"
        public static let memoryUsage = "Memory available to VM"
        public static let resourceUsageHelp = "Memory usage is reported by the Linux guest. It can be slightly lower than the configured allocation because the guest OS reserves memory for kernel and device overhead."
        public static let systemDiskUsage = "VM disk"
        public static let dataStorageUsage = "Data storage"
        public static let healthDetails = "Health details"
        public static let runtimeInstallation = "Runtime installation"
        public static let vmState = "VM state"
        public static let vmIPAddress = "VM IP"
        public static let vmErrors = "VM errors"
        public static let watchdog = "Watchdog"
        public static let vitalDBObserver = "VitalDB Observer"
        public static let redisRelay = "Redis Relay"
        public static let vitalRecorder = "Vital Recorder"
        public static let recorderHistory = "Recorder History"
        public static let recorderDetails = "Recorder Details"
        public static let bedDetails = "Bed Details"
        public static let runtimeEvents = "Runtime Events"
        public static let runtimeEventPeriod = "Period"
        public static let runtimeEventFilter = "Filter"
        public static let runtimeEventLimit = "Limit"
        public static let activeRecorderConnections = "Active recorder connections"
        public static let knownRecorders = "Known recorders"
        public static let onlineRecorders = "Online recorders"
        public static let staleRecorders = "Stale recorders"
        public static let knownBeds = "Known beds"
        public static let onlineBeds = "Online beds"
        public static let staleBeds = "Stale beds"
        public static let bedAnomalies = "Bed anomalies"
        public static let recorderAnomalies = "Recorder anomalies"
        public static let latestRecorder = "Latest recorder"
        public static let recorderObservation = "Observation updated"
        public static let recorderSource = "Recorder source"
        public static let recorderSearch = "Search VRecorder"
        public static let bedSearch = "Search Bed"
        public static let recorderStatus = "Status"
        public static let recorderVersion = "Version"
        public static let recorderLastSeen = "Last seen"
        public static let bed = "Bed"
        public static let patient = "Patient status"
        public static let anomaly = "Anomaly"
        public static let operation = "Operation"
        public static let runtimeVersion = "Runtime version"
        public static let updatedAt = "Updated at"
        public static let vmService = "VM launchd service"
        public static let proxyService = "Proxy service"
        public static let guestLogSyncService = "Guest log sync service"
        public static let sleepPreventionService = "Sleep prevention service"
        public static let watchdogService = "Watchdog service"
        public static let proxyPort = "Host proxy port"
        public static let proxyPortHelp = "Port opened on this Mac. Browsers and VRecorder devices connect to this port first, then the Helper forwards traffic into the VM."
        public static let runtimeControlPort = "Remote Console port"
        public static let runtimeControlPortHelp = "Port opened on this Mac for the Remote Console and Runtime Control API. Remote browsers can connect to this port when the Mac is reachable on the network."
        public static let vmIP = "VM IP"
        public static let guestHTTP = "Guest HTTP"
        public static let hostProxy = "Host proxy"
        public static let redisUIHTTP = "Redis UI HTTP"
        public static let swaggerUIHTTP = "Swagger UI HTTP"
        public static let failureReasons = "Failure reasons"
        public static let log = "Log"
        public static let logLines = "Lines"
        public static let logSource = "Source"
        public static let logStreaming = "Live"
        public static let logLive = "Live"
        public static let logPaused = "Paused"
        public static let advancedSummary = "Advanced runtime details"
        public static let advancedDescription = "Diagnostics, service internals, repair actions, update rollback, and administrator operations."
        public static let infoSummary = "Runtime information"
        public static let infoDescription = "Installed versions, bundled services, and deployment details for support and maintenance."
        public static let dangerZoneSummary = "Danger Zone"
        public static let dangerZoneDescription = "Operations here delete recovery assets or remove runtime components. Use them only when you understand the impact."
        public static let updateBackupDeletionHelp = "Deletes a managed update/rollback backup. This does not delete VitalServer backups."
        public static let vitalServerBackupDeletionHelp = "Deletes a selected VitalServer backup. This does not delete update rollback backups or the current runtime data."
        public static let sectionProductInfo = "Product"
        public static let sectionBundledServices = "Bundled services"
        public static let sectionRuntimePaths = "Runtime paths"
        public static let sectionRuntimeReplacement = "VM/rootfs updates"
        public static let sectionDestructiveOperations = "Destructive operations"
        public static let sectionDiagnostics = "Diagnostics"
        public static let sectionVMHealth = "VM health"
        public static let sectionServiceHealth = "Service liveness"
        public static let sectionNetworkOverrides = "Advanced network"
        public static let sectionRedisRelay = "Redis relay"
        public static let sectionVitalFileUpload = "Manual .vital upload"
        public static let sectionAdminOperations = "Admin operations"
        public static let sectionRecoveryOperations = "Recovery operations"
        public static let sectionRuntimeRepair = "Runtime repair"
        public static let sectionAdvancedRepairTools = "Advanced repair tools"
        public static let sectionUpdateRecovery = "Update recovery"
        public static let sectionRuntimeDataRecovery = "VitalServer backup"
        public static let sectionRedisDataRecovery = "Redis-only recovery"
        public static let updateBackup = "Update backup"
        public static let vitalServerBackup = "VitalServer backup"
        public static let redisBackup = "Redis-only backup"
        public static let statusReadIssues = "Status read issues"
        public static let adminOperationsHelp = "Use these actions only when administering the installed runtime. Password changes are applied with the same runtime configuration flow as Settings."
        public static let runtimeServiceControlHelp = "Starts or stops the VM, host proxy, and watchdog together. Use Stop for planned maintenance, then Start to bring VitalServer back online."
        public static let recoveryOperationsHelp = "Use these actions when the runtime is installed but unhealthy after update, rollback, or unexpected shutdown."
        public static let runtimeRepairHelp = "Use Repair Runtime first when VitalServer is unhealthy and the exact cause is unclear."
        public static let advancedRepairToolsHelp = "Use these tools only when diagnostics or support identifies a specific failure source."
        public static let updateRecoveryHelp = "Use rollback only when an update leaves the runtime unhealthy. Rollback restores the latest managed backup and restarts runtime services."
        public static let runtimeDataRecoveryHelp = "Create or restore one VitalServer backup that includes settings, runtime state, observability history, and Redis data."
        public static let redisDataRecoveryHelp = "Advanced repair action for Redis data only. Use a VitalServer backup for normal backup and restore."
        public static let redisRelayHelp = "Publishes allowlisted VitalServer Redis data from the internal Redis 3.2 source to an external Redis target. Credentials and session keys are never relayed."
        public static let redisRelayEnabled = "Enable relay"
        public static let redisRelayFinalURL = "Final URL"
        public static let redisRelayTargetURL = "Target URL"
        public static let redisRelayTargetURLHelp = "Example: redis://redis.example:6379/0. For a host or VM target, use its reachable IP address, such as redis://192.168.64.1:16381/0. TLS and username are applied from the fields below."
        public static let redisRelayUsername = "Username"
        public static let redisRelayPassword = "Password"
        public static let redisRelayClearPassword = "Clear saved password"
        public static let redisRelayTLS = "TLS"
        public static let redisRelayScope = "Data scope"
        public static let redisRelayWaveformTrendOnly = "Waveform/trend only"
        public static let redisRelayVitalReconstruction = "Vital reconstruction"
        public static let redisRelayRecorderNetworkContext = "Include recorder network context"
        public static let redisRelayPasswordConfigured = "Saved password is configured. Leave blank to keep it."
        public static let redisRelayStatus = "Relay status"
        public static let redisRelayTarget = "Target"
        public static let redisRelayBatches = "Batches"
        public static let redisRelayTotals = "Totals"
        public static let redisRelayLastBatch = "Last batch"
        public static let redisRelayLastSuccess = "Last success"
        public static let redisRelayLastError = "Last relay error"
        public static let redisRelaySettingsFingerprint = "Settings fingerprint"
        public static let sectionUpdateSource = "Update source"
        public static let sectionBundleVerification = "Bundle verification"
        public static let sectionApplyUpdate = "Apply update"
        public static let updateProgressLog = "Update progress"
        public static let offlineBundle = "Offline bundle"
        public static let onlineUpdate = "Check for Updates"
        public static let onlineUpdateUnavailable = "Online update is planned for connected sites. Use an offline bundle for this build."
        public static let selectedBundle = "Selected bundle"
        public static let updateSourceHelp = "Air-gapped sites receive an update-bundle .tar.gz file through USB, local file share, or hospital-managed storage."
        public static let bundleVerificationHelp = "Verify checksums before applying. Signature verification is currently reserved by the bundle contract."
        public static let applyUpdateHelp = "Applies the verified bundle and may restart VitalServer services. VM/rootfs level changes are treated as administrator-level updates."
        public static let menuVitalFiles = "Vital Files"
        public static let menuRuntimeServices = "Runtime Services"
        public static let noVitalFileFolders = "No vital file folders"
        public static let sectionVM = "VM"
        public static let sectionNetwork = "Network"
        public static let sectionStorage = "Storage"
        public static let sectionRedisData = "VitalServer Helper backups"
        public static let sectionOperations = "Operations"
        public static let settingsReadIssues = "Settings read issues"
        public static let sectionAdvancedConfiguration = "Advanced configuration"
        public static let cpu = "CPU"
        public static let memory = "Memory allocation"
        public static let memoryAllocationHelp = "Amount of memory assigned to the VM. The maximum is based on this Mac's memory while leaving memory for macOS. The Linux guest may report a slightly lower usable total in Status."
        public static let disk = "Disk"
        public static let mode = "Mode"
        public static let shared = "Shared"
        public static let bridged = "Bridged"
        public static let bridgedUnavailable = "Bridged (not available)"
        public static let bridgedInterface = "Bridged interface"
        public static let sharedNetworkHelp = "Shared/NAT mode is supported in this build. VitalServer is exposed through the Mac host proxy."
        public static let bridgedNetworkHelp = "Bridged mode is planned, but it requires Apple's restricted networking entitlement and is disabled for now."
        public static let sectionAdvertisedURL = "Advertised URL"
        public static let sectionAdvertisedURLOverride = "Advertised service URLs"
        public static let sectionPlannedNetworkFeatures = "Planned network features"
        public static let remoteConsoleURL = "Remote Console URL"
        public static let remoteConsoleURLHelp = "Remote browsers open this URL for the Remote Console and Runtime Control API."
        public static let vitalServerAdvertisedURL = "VitalServer URL"
        public static let vitalServerURLHelp = "URL that VitalServer should advertise to clients, such as https://vitaldb.tirosh.ai/."
        public static let remoteConsoleAdvertisedURL = "Remote Console URL"
        public static let remoteConsoleAdvertisedURLHelp = "URL for Remote Console, such as https://console.tirosh.ai/."
        public static let sectionHelperBackups = "VitalServer Helper backups"
        public static let automaticBackups = "Automatic backups"
        public static let backupTimes = "Backup times"
        public static let backupTimesHelp = "Use 24-hour HH:mm format, such as 03:15 or 15:15. Valid times are 00:00 through 23:59."
        public static let backupRetention = "Keep latest"
        public static let backupRetentionHelp = "Number of VitalServer Helper backup archives to keep, up to 30. These archives include Redis data. Older archives are pruned after a new verified backup is created."
        public static func backupTimezoneHelp(_ timezone: String) -> String {
            "Schedule timezone: \(timezone) (system local time)."
        }
        public static let appliedSettingsPrefix = "Applied"
        public static let pendingAppliedSettingsPrefix = "Not applied yet. Applied"
        public static let automaticBackupsOn = "Automatic backups on"
        public static let automaticBackupsOff = "Automatic backups off"
        public static func appliedBackupSettingsSummary(
            prefix: String,
            automaticBackupText: String,
            scheduleTimes: String,
            timezone: String,
            retentionCount: Int
        ) -> String {
            "\(prefix): \(automaticBackupText) · \(scheduleTimes) · \(timezone) · keep \(retentionCount) archives"
        }
        public static func appliedLogArchiveSettingsSummary(
            prefix: String,
            retentionDays: Int,
            maximumGiB: Int
        ) -> String {
            "\(prefix): keep \(retentionDays) days · max \(maximumGiB) GiB"
        }
        public static let sectionLogs = "Logs"
        public static let logArchiveRetention = "Log archive retention"
        public static let logArchiveRetentionHelp = "Number of days to keep managed YYYY-MM-DD log archive folders."
        public static let logArchiveMaximum = "Log archive size limit"
        public static let logArchiveMaximumHelp = "Maximum total size for managed log archive folders. Non-date folders are not automatically removed."
        public static let advertisedURLSameHost = "(same host)"
        public static let advancedNetworkHelp = "These settings change how clients discover VitalServer and Remote Console beyond this Mac's direct host proxy URLs."
        public static let mdnsName = "mDNS / Bonjour name"
        public static let mdnsHelp = "Planned. Would publish a stable .local name such as vitalserver.local from the Mac host."
        public static let bridgedNetworking = "Bridged VM networking"
        public static let bridgedAdvancedHelp = "Planned. Requires Apple restricted networking entitlement and site network approval."
        public static let httpsTermination = "HTTPS / TLS termination"
        public static let httpsTerminationHelp = "Planned. Would terminate HTTPS at the Mac proxy using a hospital CA or managed certificate."
        public static let staticVMAddress = "Static VM address"
        public static let staticVMAddressHelp = "Not available in shared/NAT mode. For bridged deployments, prefer DHCP reservation by fixed VM MAC address."
        public static let vitalFilesDirectory = "Vital files directory"
        public static let requiresVMRestart = "Requires VM restart"
        public static let requiresContainerReconcile = "Requires container reconcile"
        public static func diskIncreaseOnlyHelp(_ minimumGiB: Int) -> String {
            "Disk size can only be increased after installation. Current minimum is \(minimumGiB) GiB."
        }
        public static let startOnBoot = "Start on boot"
        public static let automaticRecovery = "Enable automatic recovery"
        public static let automaticRecoveryHelp = "Automatically restarts the VM or network proxy when VitalServer is not ready. Disable only for troubleshooting."
        public static let preventSystemSleep = "Keep Mac awake for VRecorder traffic"
        public static let preventSystemSleepHelp = "Prevents idle system sleep while VitalServer services run so the host proxy, VM, and VRecorder TCP streams stay online. The screen can still lock. Manual Sleep, lid close, shutdown, or managed power policy can still disconnect the network."
        public static let vmRuntimeRestart = "VM runtime restart"
        public static let changeActivation = "Change activation"
        public static let restartServicesAfterSave = "Activate required runtime changes after save"
        public static let resetAdminPassword = "Reset admin password"
        public static let newAdminPassword = "New admin password"
        public static let rollbackBackup = "Rollback backup"
        public static let runtimeDataBackup = "VitalServer backup"
        public static let selectedBackup = "Selected backup"
        public static let backupSize = "Backup size"
        public static let latestBackup = "Latest backup"
        public static let helperVersion = "VitalServer Helper version"
        public static let installedRuntimeVersion = "Installed runtime version"
        public static let vitalServerVersion = "VitalServer version"
        public static let appBundle = "App bundle"
        public static let runtimeHome = "Runtime home"
        public static let packageIdentifier = "Package identifier"
        public static let backupDirectory = "Backup directory"
        public static let serviceName = "Service"
        public static let serviceImage = "Image"
        public static let serviceVersion = "Version"
        public static let serviceBundled = "Bundled"
        public static let enabled = "Enabled"
        public static let status = "Status"
        public static let url = "URL"
        public static let session = "Session"
        public static let sessions = "Sessions"
        public static let messages = "Messages"
        public static let bytes = "Bytes"
        public static let lastError = "Last error"
        public static let target = "Target"
        public static let scenario = "Scenario"
        public static let signal = "Signal"
        public static let bedSetup = "Bed setup"
        public static let bedSelection = "Bed selection"
        public static let beds = "Beds"
        public static let bedCount = "Beds"
        public static let bedPrefix = "Bed prefix"
        public static let randomBedSuffix = "Random suffix"
        public static let selectedBeds = "Selected beds"
        public static let virtualVRecorderSession = "Virtual VRecorder session"
        public static let trafficProfile = "Traffic profile"
        public static let recorders = "Recorders"
        public static let recorderCount = "VRecorders"
        public static let interval = "Interval"
        public static let duration = "Duration"
        public static let maxMessages = "Max messages"
        public static let shiftTime = "Shift time"
        public static let generateFrames = "Generate frames"
        public static let vrcodeOptional = "VRecorder code (optional)"
        public static let orphanVrcode = "Orphan VRecorder code"
        public static let vmRootfsUpdatePlanned = "VM/rootfs bundle update is planned for this area. Use offline bundle updates for regular application/runtime updates."
        public static let destructiveOperationsHelp = "This build supports fresh installs only. Use Clean Uninstall only when preserved data can also be removed."
        public static let standardUninstallTemporarilyUnavailable = "Standard Uninstall is temporarily unavailable because it can leave a Mac unable to reinstall."
        public static let appBundlePath = "App bundle path"
        public static let noUpdateBundleSelected = "No update bundle selected"
        public static let unitVCPU = "vCPU"
        public static let unitGiB = "GiB"
        public static func openServiceHelp(_ serviceName: String) -> String {
            "Open \(serviceName)"
        }
    }


}
