// Generated from apps/vitalserver-macos-runtime/release.json by make vm-version-source.
// Do not edit this file directly.

enum GeneratedRelease {
    static let helperVersion = "0.1.5"
    static let minUpdaterVersion = "0.1.4"
    static let vitalServerVersion = "2.3.4"
    static let vitalServerImage = "vitalserver:2.3.4"
    static let auditProxyImage = "vitalserver-audit-proxy:0.1.0"
    static let redisImage = "redis:3.2.12-alpine"
    static let redisUIImage = "ghcr.io/joeferner/redis-commander:0.9.0"
    static let swaggerUIImage = "swaggerapi/swagger-ui:v5.17.14"
    static let guestEdgeImage = "nginx:1.24-alpine"
    static let hostProxyImage = "nginx/1.31.0"
    static let auditProxyVersion = "0.1.0"
    static let redisVersion = "3.2.12"
    static let redisUIVersion = "0.9.0"
    static let swaggerUIVersion = "5.17.14"
    static let guestEdgeVersion = "1.24"
    static let hostProxyVersion = "1.31.0"
}
