// Package hostupdaterstagedupdatecompletionapplication orchestrates a staged updater's C28-to-C27
// completion workflow. It owns no filesystem, HTTP, or layer execution state.
package hostupdaterstagedupdatecompletionapplication

import (
	"context"
	"fmt"

	"github.com/tirosh-chain/vitalserver-runtime-platform/host-updater/internal/hostupdaterdomain"
)

// StagedProductUpdatePlanningInputReader reads and authenticates C30 plus C26 through a
// Host-owned staging adapter.
type StagedProductUpdatePlanningInputReader interface {
	Read(invocationPath string) (hostupdaterdomain.StagedProductUpdatePlanningInput, error)
}

// StagedProductUpdateExecutionReportReader reads the explicit C28 evidence generated by a
// selected layer effect executor.
type StagedProductUpdateExecutionReportReader interface {
	Read(reportPath string) (hostupdaterdomain.StagedProductUpdateExecutionReport, error)
}

// StagedProductUpdateCompletionCommandPublisher publishes C27 through the explicitly selected
// Host-local transport.
type StagedProductUpdateCompletionCommandPublisher interface {
	Publish(context.Context, string, hostupdaterdomain.StagedProductUpdateCompletionCommand) error
}

// StagedProductUpdateCompletionWorkflow receives complete explicit inputs and
// delegates side effects to named ports. It never makes an update result from
// an exit log or missing evidence document.
type StagedProductUpdateCompletionWorkflow struct {
	stagedProductUpdatePlanningInputReader        StagedProductUpdatePlanningInputReader
	stagedProductUpdateExecutionReportReader      StagedProductUpdateExecutionReportReader
	stagedProductUpdateCompletionCommandPublisher StagedProductUpdateCompletionCommandPublisher
}

func NewStagedProductUpdateCompletionWorkflow(planningInputReader StagedProductUpdatePlanningInputReader, executionReportReader StagedProductUpdateExecutionReportReader, completionCommandPublisher StagedProductUpdateCompletionCommandPublisher) (*StagedProductUpdateCompletionWorkflow, error) {
	if planningInputReader == nil || executionReportReader == nil || completionCommandPublisher == nil {
		return nil, fmt.Errorf("staged product update planning input reader, execution report reader, and completion command publisher are required")
	}
	return &StagedProductUpdateCompletionWorkflow{
		stagedProductUpdatePlanningInputReader:        planningInputReader,
		stagedProductUpdateExecutionReportReader:      executionReportReader,
		stagedProductUpdateCompletionCommandPublisher: completionCommandPublisher,
	}, nil
}

// PublishStagedProductUpdateCompletion reads C30/C26 and C28, constructs the pure C27 command, and
// publishes it to one explicit Host-local endpoint.
func (workflow *StagedProductUpdateCompletionWorkflow) PublishStagedProductUpdateCompletion(ctx context.Context, invocationPath string, reportPath string, completionEndpoint string) (hostupdaterdomain.StagedProductUpdateCompletionCommand, error) {
	if completionEndpoint == "" {
		return hostupdaterdomain.StagedProductUpdateCompletionCommand{}, fmt.Errorf("Host-local completion endpoint is required")
	}
	input, err := workflow.stagedProductUpdatePlanningInputReader.Read(invocationPath)
	if err != nil {
		return hostupdaterdomain.StagedProductUpdateCompletionCommand{}, fmt.Errorf("read staged product update planning input: %w", err)
	}
	report, err := workflow.stagedProductUpdateExecutionReportReader.Read(reportPath)
	if err != nil {
		return hostupdaterdomain.StagedProductUpdateCompletionCommand{}, fmt.Errorf("read staged product update execution report: %w", err)
	}
	command, err := hostupdaterdomain.ComposeStagedProductUpdateCompletionCommand(input, report)
	if err != nil {
		return hostupdaterdomain.StagedProductUpdateCompletionCommand{}, fmt.Errorf("compose staged product update completion command: %w", err)
	}
	if err := workflow.stagedProductUpdateCompletionCommandPublisher.Publish(ctx, completionEndpoint, command); err != nil {
		return hostupdaterdomain.StagedProductUpdateCompletionCommand{}, fmt.Errorf("publish staged product update completion command: %w", err)
	}
	return command, nil
}
