public enum RuntimeFileNames {
    public static let rootfsBase = "rootfs-base.raw.gz"
    public static let runtimeVersion = "runtime-version.json"
    public static let backupManifest = "backup-manifest.json"
    public static let updateBundleManifest = "manifest.json"
    public static let runtimeStatus = "runtime-status.json"
    public static let runtimeOperationLease = "runtime-operation-lease.json"
    public static let runtimeEvents = "runtime-events.jsonl"
    public static let runtimeObservabilityDB = "runtime-observability.sqlite"
    public static let appliedVMConfig = "applied-vm-config.json"
    public static let hostTime = "host-time.json"
    public static let runtimeInstallState = "tirosh-vitalserver-install-state.json"
    public static let runtimeUninstallState = "tirosh-vitalserver-uninstall-state.json"
    public static let vmIP = "vm-ip"
    public static let vmLifecycle = "vm-lifecycle.json"
    public static let runtimeState = "runtime-state.json"
    public static let bootstrapLog = "bootstrap.log"
    public static let bootstrapResult = "bootstrap-result.json"
    public static let datastoreRepairLog = "repair-datastore.log"
    public static let redisBackupLog = "redis-backup.log"
    public static let redisRestoreLog = "redis-restore.log"
    public static let updateActivationLog = "activate-update.log"
    public static let updateShutdownLog = "prepare-update-shutdown.log"
    public static let containerLogs = "container-logs.log"
    public static let managerCommandLog = "tirosh-vitalserver-manager-command.log"
    public static let managerHelperMessageLog = "tirosh-vitalserver-helper-message.log"
}
