// Generated from apps/vitalserver-macos-runtime/release.json by make vm-version-source.
// Do not edit this file directly.

import Contracts

extension Constants {
    static let launcherVersion = "0.1.6"
    static let launcherChannel = UpdateBundleChannel(rawValue: "stable")
}
