// Generated from release-dev.json by make vm-version-source.
// Do not edit this file directly.

import Contracts

extension Constants {
    static let launcherVersion = "0.1.10"
    static let launcherChannel = UpdateBundleChannel(
        rawValue: "dev"
    )
    static let testkitContainerIncluded = true
}
