import Bootstrap

typealias RuntimeWatchdogRunnerCompositionContext = Bootstrap.RuntimeWatchdogRunnerCompositionContext
typealias RuntimeWatchdogRunnerCompositionOperations = Bootstrap.RuntimeWatchdogRunnerCompositionOperations
typealias RuntimeWatchdogRunnerComposition = Bootstrap.RuntimeWatchdogRunnerComposition
