import Workflow

typealias RuntimeGuestRuntimeStateObservation = Workflow.RuntimeGuestRuntimeStateObservation
typealias RuntimeGuestRuntimeStateObservationReader = Workflow.RuntimeGuestRuntimeStateObservationReader
