import Bootstrap

typealias RuntimeHealthWaitRunnerCompositionOperations = Bootstrap.RuntimeHealthWaitRunnerCompositionOperations
typealias RuntimeHealthWaitRunnerComposition = Bootstrap.RuntimeHealthWaitRunnerComposition
