import Bootstrap

typealias RuntimeUninstallCompositionContext = Bootstrap.RuntimeUninstallCompositionContext
typealias RuntimeUninstallCompositionOperations = Bootstrap.RuntimeUninstallCompositionOperations
typealias RuntimeUninstallComposition = Bootstrap.RuntimeUninstallComposition
