import Bootstrap

typealias RuntimeStatusWriterCompositionOperations = Bootstrap.RuntimeStatusWriterCompositionOperations
typealias RuntimeStatusWriterComposition = Bootstrap.RuntimeStatusWriterComposition
