import Bootstrap

typealias RuntimeGuestShutdownCompositionContext = Bootstrap.RuntimeGuestShutdownCompositionContext
typealias RuntimeGuestShutdownCompositionOperations = Bootstrap.RuntimeGuestShutdownCompositionOperations
typealias RuntimeGuestShutdownComposition = Bootstrap.RuntimeGuestShutdownComposition
