import Bootstrap

typealias RuntimeServiceControlCompositionOperations = Bootstrap.RuntimeServiceControlCompositionOperations
typealias RuntimeServiceControlComposition = Bootstrap.RuntimeServiceControlComposition
