import Bootstrap

typealias RuntimeGuestActivationCompositionContext = Bootstrap.RuntimeGuestActivationCompositionContext
typealias RuntimeGuestActivationCompositionOperations = Bootstrap.RuntimeGuestActivationCompositionOperations
typealias RuntimeGuestActivationComposition = Bootstrap.RuntimeGuestActivationComposition
