import Bootstrap

typealias RuntimeBackupStoreCompositionContext = Bootstrap.RuntimeBackupStoreCompositionContext
typealias RuntimeBackupStoreCompositionOperations = Bootstrap.RuntimeBackupStoreCompositionOperations
typealias RuntimeBackupStoreComposition = Bootstrap.RuntimeBackupStoreComposition
