import Bootstrap

typealias RuntimeHealthCheckRunnerCompositionOperations = Bootstrap.RuntimeHealthCheckRunnerCompositionOperations
typealias RuntimeHealthCheckRunnerComposition = Bootstrap.RuntimeHealthCheckRunnerComposition
