import HostAdapters

typealias RuntimeHostProxyPortCleanerError = HostAdapters.RuntimeHostProxyPortCleanerError
typealias RuntimeProxyNginxPIDReadResult = HostAdapters.RuntimeProxyNginxPIDReadResult
typealias RuntimeHostProxyPortCleaner = HostAdapters.RuntimeHostProxyPortCleaner
