import Bootstrap

typealias RuntimeDatastoreRepairCompositionContext = Bootstrap.RuntimeDatastoreRepairCompositionContext
typealias RuntimeDatastoreRepairCompositionOperations = Bootstrap.RuntimeDatastoreRepairCompositionOperations
typealias RuntimeDatastoreRepairComposition = Bootstrap.RuntimeDatastoreRepairComposition
