enum AppConstants {
    enum Product {
        static let displayName = "VitalServer Helper"
        static let poweredByPrefix = "powered by"
        static let tiroshName = "Tirosh"
        static let tiroshURL = "https://www.tirosh.ai/"
        static let packageIdentifier = "com.tirosh.vitalserver.vm"
        static let vitalServerVersion = "2.3.4"
        static let defaultProxyPort = 80
        static func vitalServerURL(proxyPort: Int) -> String {
            "http://127.0.0.1:\(proxyPort)/"
        }
        static func redisUIURL(proxyPort: Int) -> String {
            "http://127.0.0.1:\(proxyPort)/redis-ui/"
        }
        static func swaggerURL(proxyPort: Int) -> String {
            "http://127.0.0.1:\(proxyPort)/swagger/"
        }
        static func hostProxyHealthURL(proxyPort: Int) -> String {
            "http://127.0.0.1:\(proxyPort)/check"
        }
        static func guestHealthURL(vmIP: String) -> String {
            "http://\(vmIP)/check"
        }
    }

    enum SettingsLimits {
        static let minimumCPUCount = 7
        static let maximumCPUCount = 64
        static let defaultDiskGiB = 32
        static let minimumDiskGiB = 4
        static let maximumDiskGiB = 512
        static let diskStepGiB = 4
        static let minimumMemoryGiB = 4
        static let maximumMemoryGiB = 64
        static let memoryStepGiB = 4
    }

    enum ServiceVersions {
        static let vitalServerImage = "vitalserver:2.3.4"
        static let redisImage = "redis:3.2.12-alpine"
        static let redisUIImage = "ghcr.io/joeferner/redis-commander:0.9.0"
        static let swaggerUIImage = "swaggerapi/swagger-ui:v5.17.14"
        static let guestEdgeImage = "nginx:1.24-alpine"
        static let hostProxy = "nginx/1.31.0"
    }

    enum Labels {
        static let tabStatus = "Status"
        static let tabSettings = "Settings"
        static let tabUpdate = "Update"
        static let tabAdvanced = "Advanced"
        static let tabInfo = "About"
        static let tabDangerZone = "Danger Zone"
        static let tabLog = "Logs"
        static let runtime = "Runtime"
        static let runtimeState = "Runtime state"
        static let vitalServer = "VitalServer"
        static let vitalServerURL = "VitalServer URL"
        static let dataDirectory = "Data directory"
        static let overallHealth = "Overall health"
        static let resourceUsage = "Resource usage"
        static let cpuUsage = "CPU"
        static let memoryUsage = "Memory"
        static let systemDiskUsage = "VM disk"
        static let dataStorageUsage = "Data storage"
        static let healthDetails = "Health details"
        static let managerRuntime = "Helper runtime"
        static let vmIPAddress = "VM IP"
        static let vitalServerApp = "VitalServer"
        static let hostProxyService = "Network access"
        static let redis = "Redis"
        static let redisUI = "Redis UI"
        static let swaggerUI = "Swagger UI"
        static let watchdog = "Watchdog"
        static let operation = "Operation"
        static let runtimeVersion = "Runtime version"
        static let updatedAt = "Updated at"
        static let vmService = "VM service"
        static let proxyService = "Proxy service"
        static let watchdogService = "Watchdog service"
        static let proxyPort = "Mac listen port"
        static let proxyPortHelp = "Port opened on this Mac. Browsers and VRecorder devices connect to this port first, then the Helper forwards traffic into the VM."
        static let vmIP = "VM IP"
        static let guestHTTP = "Guest HTTP"
        static let hostProxy = "Host proxy"
        static let redisUIHTTP = "Redis UI HTTP"
        static let swaggerUIHTTP = "Swagger UI HTTP"
        static let failureReasons = "Failure reasons"
        static let log = "Log"
        static let logLines = "Lines"
        static let logSource = "Source"
        static let logStreaming = "Live"
        static let logLive = "Live"
        static let logPaused = "Paused"
        static let advancedSummary = "Advanced runtime details"
        static let advancedDescription = "Diagnostics, service internals, proxy repair, update rollback, and uninstall tools for administrators."
        static let infoSummary = "Runtime information"
        static let infoDescription = "Installed versions, bundled services, and deployment details for support and maintenance."
        static let dangerZoneSummary = "Danger Zone"
        static let dangerZoneDescription = "Operations here can restart, roll back, replace, or remove runtime components. Use them only when you understand the impact."
        static let sectionProductInfo = "Product"
        static let sectionBundledServices = "Bundled services"
        static let sectionRuntimePaths = "Runtime paths"
        static let sectionRuntimeReplacement = "VM/rootfs updates"
        static let sectionDestructiveOperations = "Destructive operations"
        static let sectionDiagnostics = "Diagnostics"
        static let sectionServiceHealth = "Service health"
        static let sectionNetworkOverrides = "Advanced network"
        static let sectionAdminOperations = "Admin operations"
        static let sectionRecoveryOperations = "Recovery operations"
        static let sectionUpdateRecovery = "Update recovery"
        static let adminOperationsHelp = "Use these actions only when administering the installed runtime. Password changes are applied with the same runtime configuration flow as Settings."
        static let recoveryOperationsHelp = "Use repair actions when the runtime is installed but unhealthy after update, rollback, or unexpected shutdown."
        static let updateRecoveryHelp = "Use rollback only when an update leaves the runtime unhealthy. Rollback restores the latest managed backup and restarts runtime services."
        static let sectionUpdateSource = "Update source"
        static let sectionBundleVerification = "Bundle verification"
        static let sectionApplyUpdate = "Apply update"
        static let updateProgressLog = "Update progress"
        static let offlineBundle = "Offline bundle"
        static let onlineUpdate = "Online update"
        static let onlineUpdateUnavailable = "Online update is planned for connected sites. Use an offline bundle for this build."
        static let selectedBundle = "Selected bundle"
        static let updateSourceHelp = "Air-gapped sites receive an update-bundle directory through USB, local file share, or hospital-managed storage."
        static let bundleVerificationHelp = "Verify checksums before applying. Signature verification is currently reserved by the bundle contract."
        static let applyUpdateHelp = "Applies the verified bundle and may restart VitalServer services. VM/rootfs level changes are treated as administrator-level updates."
        static let menuVitalFiles = "Vital Files"
        static let menuRuntimeServices = "Runtime Services"
        static let noVitalFileFolders = "No vital file folders"
        static let sectionVM = "VM"
        static let sectionNetwork = "Network"
        static let sectionStorage = "Storage"
        static let sectionOperations = "Operations"
        static let sectionAdvancedConfiguration = "Advanced configuration"
        static let cpu = "CPU"
        static let memory = "Memory"
        static let disk = "Disk"
        static let mode = "Mode"
        static let shared = "Shared"
        static let bridged = "Bridged"
        static let bridgedUnavailable = "Bridged (not available)"
        static let bridgedInterface = "Bridged interface"
        static let sharedNetworkHelp = "Shared/NAT mode is supported in this build. VitalServer is exposed through the Mac host proxy."
        static let bridgedNetworkHelp = "Bridged mode is planned, but it requires Apple's restricted networking entitlement and is disabled for now."
        static let sectionMacExposure = "Mac exposure"
        static let sectionAdvertisedURL = "Advertised URL"
        static let sectionPlannedNetworkFeatures = "Planned network features"
        static let publicHost = "Advertised host"
        static let publicHostHelp = "Optional host name or IP written into VitalServer runtime config. Leave empty when devices should use the same host they connected to."
        static let publicPort = "Advertised port"
        static let publicPortHelp = "Port that VitalServer should advertise to clients. In most shared/NAT installs this should match the Mac listen port."
        static let advertisedURLPreview = "Advertised URL preview"
        static let advertisedURLSameHost = "(same host)"
        static let advancedNetworkHelp = "These settings change how VitalServer is exposed outside the VM. Use them when the Mac is behind a hospital network policy, reverse proxy, or fixed endpoint."
        static let mdnsName = "mDNS / Bonjour name"
        static let mdnsHelp = "Planned. Would publish a stable .local name such as vitalserver.local from the Mac host."
        static let bridgedNetworking = "Bridged VM networking"
        static let bridgedAdvancedHelp = "Planned. Requires Apple restricted networking entitlement and site network approval."
        static let httpsTermination = "HTTPS / TLS termination"
        static let httpsTerminationHelp = "Planned. Would terminate HTTPS at the Mac proxy using a hospital CA or managed certificate."
        static let staticVMAddress = "Static VM address"
        static let staticVMAddressHelp = "Not available in shared/NAT mode. For bridged deployments, prefer DHCP reservation by fixed VM MAC address."
        static let vitalFilesDirectory = "Vital files directory"
        static func diskIncreaseOnlyHelp(_ minimumGiB: Int) -> String {
            "Disk size can only be increased after installation. Current minimum is \(minimumGiB) GiB."
        }
        static let startOnBoot = "Start on boot"
        static let restartServicesAfterSave = "Restart services after save"
        static let resetAdminPassword = "Reset admin password"
        static let newAdminPassword = "New admin password"
        static let rollbackBackup = "Rollback backup"
        static let selectedBackup = "Selected backup"
        static let backupSize = "Backup size"
        static let latestBackup = "Latest backup"
        static let helperVersion = "VitalServer Helper version"
        static let installedRuntimeVersion = "Installed runtime version"
        static let vitalServerVersion = "VitalServer version"
        static let appBundle = "App bundle"
        static let runtimeHome = "Runtime home"
        static let packageIdentifier = "Package identifier"
        static let backupDirectory = "Backup directory"
        static let serviceName = "Service"
        static let serviceImage = "Image"
        static let serviceVersion = "Version"
        static let vmRootfsUpdatePlanned = "VM/rootfs bundle update is planned for this area. Use offline bundle updates for regular application/runtime updates."
        static let destructiveOperationsHelp = "Uninstall removes installed services and runtime files. Choose clean uninstall only when preserved data can also be removed."
        static let appBundlePath = "App bundle path"
        static let noUpdateBundleSelected = "No update bundle selected"
        static let unitVCPU = "vCPU"
        static let unitGiB = "GiB"
        static func openServiceHelp(_ serviceName: String) -> String {
            "Open \(serviceName)"
        }
    }

    enum Values {
        static let networkShared = "shared"
        static let networkBridged = "bridged"
        static let stateHealthy = "healthy"
        static let stateInstalling = "installing"
        static let stateUpdating = "updating"
        static let stateRecovering = "recovering"
        static let stateDegraded = "degraded"
        static let stateCritical = "critical"
        static let launchdLoaded = "loaded"
        static let boolTrue = "true"
        static let boolFalse = "false"
    }

    enum RuntimeCommand {
        static let runtime = "runtime"
        static let configure = "configure"
        static let applyBundle = "apply-bundle"
        static let verifyBundle = "verify-bundle"
        static let rollback = "rollback"
        static let repairDatastore = "repair-datastore"
        static let optionCPU = "--cpu"
        static let optionMemoryGiB = "--memory-gib"
        static let optionDiskGiB = "--disk-gib"
        static let optionNetwork = "--network"
        static let optionProxyPort = "--proxy-port"
        static let optionVitalFilesDirectory = "--vital-files-dir"
        static let optionPublicHost = "--public-host"
        static let optionPublicPort = "--public-port"
        static let optionStartOnBoot = "--start-on-boot"
        static let optionBridgedInterface = "--bridged-interface"
        static let optionAdminPasswordFile = "--admin-password-file"
        static let optionRestart = "--restart"
    }

    enum Environment {
        static let vmHome = "VITALSERVER_VM_HOME"
    }

    enum Actions {
        static let healthCheck = "Health Check"
        static let open = "Open"
        static let openVitalServer = "VitalServer"
        static let openRedisUI = "Redis UI"
        static let openSwagger = "Swagger"
        static let openVitalFilesDirectory = "Open Vital Files Directory"
        static let repairProxy = "Repair Proxy"
        static let repairProxyPort = "Repair Proxy Port"
        static let repairDatastore = "Repair Data Store"
        static let uninstall = "Uninstall"
        static let standardUninstall = "Uninstall..."
        static let cleanUninstall = "Clean Uninstall..."
        static let vmRootfsUpdate = "VM/rootfs Update"
        static let refresh = "Refresh"
        static let applySettings = "Apply"
        static let chooseDirectory = "Choose..."
        static let chooseBundle = "Choose Bundle"
        static let verifyBundle = "Verify"
        static let applyBundle = "Apply Bundle"
        static let rollback = "Rollback"
        static let deleteBackup = "Delete Backup"
        static let openLogs = "Open Logs"
        static let startUpdate = "Start Update"
        static let startRollback = "Start Rollback"
        static let ok = "OK"
        static let cancel = "Cancel"
        static let continueAction = "Continue"
        static let back = "Back"
        static let install = "Install"
    }

    enum StatusText {
        static let ready = "Ready"
        static let available = "Available"
        static let unavailable = "Unavailable"
        static let healthy = "Healthy"
        static let starting = "Starting"
        static let needsAttention = "Needs attention"
        static let critical = "Critical"
        static let running = "Running"
        static let reachable = "Reachable"
        static let needsRepair = "Needs repair"
        static let installed = "Installed"
        static let notInstalled = "Not installed"
        static let loaded = "Loaded"
        static let notLoaded = "Not loaded"
        static let waiting = "Waiting"
        static let notChecked = "Not checked"
        static let planned = "Planned"
        static let notAvailable = "Not available"
        static let noLogData = "No log data for this source yet."
        static let unknown = "Unknown"
        static let failed = "failed"
        static let done = "Done"
        static let healthCheckCompleted = "Health check completed"
        static let missingUninstaller = "Missing uninstaller"
        static let uninstallPreparing = "Preparing runtime removal..."
        static let uninstallWaitingForPrivilege = "Waiting for administrator approval..."
        static let uninstallRunning = "Removing runtime..."
        static let uninstallCompleted = "Runtime removal completed."
        static let cleanUninstallCompleted = "Runtime and preserved data removal completed."
        static let applicationWillQuit = "The Helper app will quit now."
        static let proxyRepairPreparing = "Preparing host proxy repair..."
        static let proxyRepairRunning = "Repairing host proxy..."
        static let proxyRepairCompleted = "Host proxy repair completed."
        static let datastoreRepairPreparing = "Preparing data store repair..."
        static let datastoreRepairRunning = "Repairing data store..."
        static let datastoreRepairCompleted = "Data store repair completed."
        static let settingsApplyPreparing = "Preparing runtime settings..."
        static let settingsApplyRunning = "Applying runtime settings..."
        static let settingsApplied = "Runtime settings applied."
        static let applySettingsConfirmation = "Apply these settings to the installed runtime?\n\nThis may update launchd services, rewrite runtime configuration, and restart the VM/proxy services when restart is enabled."
        static let updateBundleApplied = "Update bundle applied."
        static let updateBundleAppliedRelaunching = "Update bundle applied. Relaunching VitalServer Helper..."
        static let updateBundlePreparing = "Preparing update bundle..."
        static let updateBundleApplying = "Applying update bundle..."
        static let updateBundleVerifying = "Verifying update bundle..."
        static let updateBundleVerified = "Update bundle verified."
        static let updateBundleVerificationFailed = "Update bundle verification failed."
        static let updateBundleNotVerified = "Verify the update bundle before applying it."
        static let updateBundleConfirmation = "Apply this verified bundle?\n\nThis may restart VitalServer services. Detailed progress is written to the Command log and Update activation log."
        static let rollbackCompleted = "Rollback completed."
        static let rollbackPreparing = "Preparing rollback..."
        static let rollbackRunning = "Rolling back runtime..."
        static let backupDeleted = "Backup deleted."
        static let backupDeletePreparing = "Preparing backup deletion..."
        static let backupDeleteRunning = "Deleting backup..."
        static let missingBackup = "Choose a backup first."
        static let invalidBackup = "Selected backup is outside the managed backup directory."
        static let missingLauncher = "Missing runtime launcher"
        static let missingBundle = "Choose an update bundle first."
        static let commandCancelled = "Command was cancelled or failed."
        static let latestBackupFallback = "Latest backup"
        static let repairProxyConfirmation = "Stops nginx listeners on the configured proxy port, then restarts the host proxy service. Other process types are reported but not stopped automatically."
        static let repairDatastoreConfirmation = "Checks and repairs the Redis append-only file inside the VM, then restarts VitalServer containers and host services. Redis creates a timestamped backup before fixing a damaged AOF file."
        static let standardUninstallConfirmation = "Removes the Helper app, runtime services, tools, VM disk, logs, and package receipt. Vital files and backups are preserved."
        static let cleanUninstallConfirmation = "Removes the Helper app, runtime services, tools, VM disk, logs, backups, and configured vital files directory."
        static let deleteBackupConfirmation = "Delete the selected managed backup? This cannot be undone."
        static let bridgedModeUnavailable = "Bridged mode is not available in this build."
        static let diskDecreaseUnavailable = "Disk size can only be increased."
        static let vitalFilesDirectoryRequired = "Vital files directory must be an absolute path."
        static let invalidPort = "Port must be between 1 and 65535."
        static let adminPasswordRequired = "Admin password reset value must not be empty."
        static let adminPasswordNewline = "Admin password reset value must not contain newlines."
        static func commandFailed(exitCode: Int32) -> String {
            "Command failed with exit code \(exitCode)"
        }
    }

    enum Notifications {
        static let needsAttentionTitle = "VitalServer needs attention"
        static let criticalTitle = "VitalServer is critical"
        static let recoveredTitle = "VitalServer recovered"
        static let needsAttentionBody = "Open VitalServer Helper to review runtime health details."
        static let criticalBody = "VitalServer runtime requires administrator attention."
        static let recoveredBody = "All monitored runtime services are healthy again."
    }

    enum Paths {
        static let vmHome = "/Library/Application Support/TiroshVitalServer/vm"
        static let launcher = "/usr/local/bin/vitalserver-vm"
        static let uninstaller = "/usr/local/bin/tirosh-vitalserver-uninstall"
        static let vmIPFile = "/Library/Application Support/TiroshVitalServer/vm/data/run/vm-ip"
        static let runtimeState = "/Library/Application Support/TiroshVitalServer/vm/data/run/runtime-state.json"
        static let runtimeStatus = "/Library/Application Support/TiroshVitalServer/status/runtime-status.json"
        static let managerApp = "/Applications/VitalServer Helper.app"
        static let installLog = "/Library/Application Support/TiroshVitalServer/logs/install.log"
        static let runtimeLogs = "/Library/Application Support/TiroshVitalServer/vm/logs"
        static let containerLogs = "/Library/Application Support/TiroshVitalServer/vm/data/run/container-logs.log"
        static let updateActivationLog = "/Library/Application Support/TiroshVitalServer/vm/data/run/activate-update.log"
        static let backups = "/Library/Application Support/TiroshVitalServer/backups"
        static let vmConfig = "/Library/Application Support/TiroshVitalServer/vm/runtime/vm-config.json"
        static let vmDisk = "/Library/Application Support/TiroshVitalServer/vm/runtime/vm-disk.img"
        static let guestRuntimeConfig = "/Library/Application Support/TiroshVitalServer/vm/data/deploy/runtime-config.json"
        static let proxyNginxPid = "/Library/Application Support/TiroshVitalServer/nginx/logs/nginx.pid"
        static let proxyLaunchDaemon = "/Library/LaunchDaemons/com.tirosh.vitalserver-proxy.plist"
        static let commandLogFile = "/private/tmp/tirosh-vitalserver-manager-command.log"
    }

    enum Launchd {
        static let vmService = "com.tirosh.vitalserver-vm"
        static let proxyService = "com.tirosh.vitalserver-proxy"
        static let watchdogService = "com.tirosh.vitalserver-watchdog"
    }

    enum Commands {
        static let osascript = "/usr/bin/osascript"
        static let shell = "/bin/sh"
        static let env = "/usr/bin/env"
        static let open = "/usr/bin/open"
        static let sleep = "/bin/sleep"
        static let curl = "/usr/bin/curl"
        static let launchctl = "/bin/launchctl"
        static let lsof = "/usr/sbin/lsof"
        static let rm = "/bin/rm"
    }
}
