enum AppConstants {
    enum Product {
        static let displayName = "VitalServer Helper"
        static let poweredBy = "powered by Tirosh"
        static let subtitle = "Manage the dedicated Mac runtime"
        static let defaultProxyPort = 80
        static func vitalServerURL(proxyPort: Int) -> String {
            "http://127.0.0.1:\(proxyPort)/"
        }
        static func redisUIURL(proxyPort: Int) -> String {
            "http://127.0.0.1:\(proxyPort)/redis-ui/"
        }
        static func swaggerURL(proxyPort: Int) -> String {
            "http://127.0.0.1:\(proxyPort)/swagger/"
        }
        static func hostProxyHealthURL(proxyPort: Int) -> String {
            "http://127.0.0.1:\(proxyPort)/"
        }
        static func guestHealthURL(vmIP: String) -> String {
            "http://\(vmIP)/"
        }
    }

    enum Labels {
        static let tabStatus = "Status"
        static let tabSettings = "Settings"
        static let tabUpdate = "Update"
        static let tabAdvanced = "Advanced"
        static let tabLog = "Log"
        static let runtime = "Runtime"
        static let runtimeState = "Runtime state"
        static let vitalServer = "VitalServer"
        static let vitalServerURL = "VitalServer URL"
        static let dataDirectory = "Data directory"
        static let overallHealth = "Overall health"
        static let healthDetails = "Health details"
        static let managerRuntime = "Helper runtime"
        static let vmIPAddress = "VM IP"
        static let vitalServerApp = "VitalServer app"
        static let hostProxyService = "Host proxy"
        static let redisUI = "Redis UI"
        static let swaggerUI = "Swagger UI"
        static let watchdog = "Watchdog"
        static let operation = "Operation"
        static let runtimeVersion = "Runtime version"
        static let updatedAt = "Updated at"
        static let vmService = "VM service"
        static let proxyService = "Proxy service"
        static let watchdogService = "Watchdog service"
        static let proxyPort = "Host proxy port"
        static let vmIP = "VM IP"
        static let guestHTTP = "Guest HTTP"
        static let hostProxy = "Host proxy"
        static let redisUIHTTP = "Redis UI HTTP"
        static let swaggerUIHTTP = "Swagger UI HTTP"
        static let failureReasons = "Failure reasons"
        static let log = "Log"
        static let logLines = "Lines"
        static let advancedSummary = "Advanced runtime details"
        static let advancedDescription = "Diagnostics, service internals, proxy repair, update rollback, and uninstall tools for administrators."
        static let menuVitalFiles = "Vital Files"
        static let menuRuntimeServices = "Runtime Services"
        static let noVitalFileFolders = "No vital file folders"
        static let sectionVM = "VM"
        static let sectionNetwork = "Network"
        static let sectionStorage = "Storage"
        static let sectionOperations = "Operations"
        static let sectionAdvancedConfiguration = "Advanced configuration"
        static let cpu = "CPU"
        static let memory = "Memory"
        static let disk = "Disk"
        static let mode = "Mode"
        static let shared = "Shared"
        static let bridged = "Bridged"
        static let bridgedUnavailable = "Bridged (not available)"
        static let bridgedInterface = "Bridged interface"
        static let sharedNetworkHelp = "Shared/NAT mode is supported in this build. VitalServer is exposed through the Mac host proxy."
        static let bridgedNetworkHelp = "Bridged mode is planned, but it requires Apple's restricted networking entitlement and is disabled for now."
        static let publicHost = "Public host"
        static let publicPort = "Public URL port"
        static let vitalFilesDirectory = "Vital files directory"
        static func diskIncreaseOnlyHelp(_ minimumGiB: Int) -> String {
            "Disk size can only be increased after installation. Current minimum is \(minimumGiB) GB."
        }
        static let startOnBoot = "Start on boot"
        static let restartServicesAfterSave = "Restart services after save"
        static let resetAdminPassword = "Reset admin password"
        static let newAdminPassword = "New admin password"
        static let rollbackBackup = "Rollback backup"
        static let latestBackup = "Latest backup"
        static let noUpdateBundleSelected = "No update bundle selected"
        static let unitVCPU = "vCPU"
        static let unitGiB = "GB"
    }

    enum Values {
        static let networkShared = "shared"
        static let networkBridged = "bridged"
        static let stateHealthy = "healthy"
        static let stateInstalling = "installing"
        static let stateUpdating = "updating"
        static let stateRecovering = "recovering"
        static let stateDegraded = "degraded"
        static let stateCritical = "critical"
        static let launchdLoaded = "loaded"
        static let boolTrue = "true"
        static let boolFalse = "false"
    }

    enum RuntimeCommand {
        static let runtime = "runtime"
        static let configure = "configure"
        static let applyBundle = "apply-bundle"
        static let verifyBundle = "verify-bundle"
        static let rollback = "rollback"
        static let optionCPU = "--cpu"
        static let optionMemoryGiB = "--memory-gib"
        static let optionDiskGiB = "--disk-gib"
        static let optionNetwork = "--network"
        static let optionProxyPort = "--proxy-port"
        static let optionVitalFilesDirectory = "--vital-files-dir"
        static let optionPublicHost = "--public-host"
        static let optionPublicPort = "--public-port"
        static let optionStartOnBoot = "--start-on-boot"
        static let optionBridgedInterface = "--bridged-interface"
        static let optionAdminPasswordFile = "--admin-password-file"
        static let optionRestart = "--restart"
    }

    enum Environment {
        static let vmHome = "VITALSERVER_VM_HOME"
    }

    enum Actions {
        static let healthCheck = "Health Check"
        static let open = "Open"
        static let openVitalServer = "VitalServer"
        static let openRedisUI = "Redis UI"
        static let openSwagger = "Swagger"
        static let openVitalFilesDirectory = "Open Vital Files Directory"
        static let repairProxy = "Repair Proxy"
        static let repairProxyPort = "Repair Proxy Port"
        static let uninstall = "Uninstall"
        static let standardUninstall = "Uninstall..."
        static let cleanUninstall = "Clean Uninstall..."
        static let refresh = "Refresh"
        static let applySettings = "Apply"
        static let chooseDirectory = "Choose..."
        static let chooseBundle = "Choose Bundle"
        static let verifyBundle = "Verify"
        static let applyBundle = "Apply Bundle"
        static let rollback = "Rollback"
        static let openLogs = "Open Logs"
        static let startUpdate = "Start Update"
        static let startRollback = "Start Rollback"
        static let ok = "OK"
        static let cancel = "Cancel"
        static let continueAction = "Continue"
        static let back = "Back"
        static let install = "Install"
    }

    enum StatusText {
        static let ready = "Ready"
        static let available = "Available"
        static let unavailable = "Unavailable"
        static let healthy = "Healthy"
        static let starting = "Starting"
        static let needsAttention = "Needs attention"
        static let critical = "Critical"
        static let running = "Running"
        static let reachable = "Reachable"
        static let needsRepair = "Needs repair"
        static let installed = "Installed"
        static let notInstalled = "Not installed"
        static let loaded = "Loaded"
        static let notLoaded = "Not loaded"
        static let waiting = "Waiting"
        static let notChecked = "Not checked"
        static let unknown = "Unknown"
        static let failed = "failed"
        static let done = "Done"
        static let healthCheckCompleted = "Health check completed"
        static let missingUninstaller = "Missing uninstaller"
        static let uninstallPreparing = "Preparing runtime removal..."
        static let uninstallWaitingForPrivilege = "Waiting for administrator approval..."
        static let uninstallRunning = "Removing runtime..."
        static let uninstallCompleted = "Runtime removal completed."
        static let cleanUninstallCompleted = "Runtime and preserved data removal completed."
        static let applicationWillQuit = "The Helper app will quit now."
        static let proxyRepairPreparing = "Preparing host proxy repair..."
        static let proxyRepairRunning = "Repairing host proxy..."
        static let proxyRepairCompleted = "Host proxy repair completed."
        static let settingsApplyPreparing = "Preparing runtime settings..."
        static let settingsApplyRunning = "Applying runtime settings..."
        static let settingsApplied = "Runtime settings applied."
        static let applySettingsConfirmation = "Apply these settings to the installed runtime?\n\nThis may update launchd services, rewrite runtime configuration, and restart the VM/proxy services when restart is enabled."
        static let updateBundleApplied = "Update bundle applied."
        static let updateBundleVerifying = "Verifying update bundle..."
        static let updateBundleVerified = "Update bundle verified."
        static let updateBundleVerificationFailed = "Update bundle verification failed."
        static let updateBundleNotVerified = "Verify the update bundle before applying it."
        static let rollbackCompleted = "Rollback completed."
        static let missingLauncher = "Missing runtime launcher"
        static let missingBundle = "Choose an update bundle first."
        static let commandCancelled = "Command was cancelled or failed."
        static let latestBackupFallback = "Latest backup"
        static let repairProxyConfirmation = "Stops nginx listeners on the configured proxy port, then restarts the host proxy service. Other process types are reported but not stopped automatically."
        static let standardUninstallConfirmation = "Removes the Helper app, runtime services, tools, VM disk, logs, and package receipt. Vital files and backups are preserved."
        static let cleanUninstallConfirmation = "Removes the Helper app, runtime services, tools, VM disk, logs, backups, and configured vital files directory."
        static let bridgedModeUnavailable = "Bridged mode is not available in this build."
        static let diskDecreaseUnavailable = "Disk size can only be increased."
        static let vitalFilesDirectoryRequired = "Vital files directory must be an absolute path."
        static let invalidPort = "Port must be between 1 and 65535."
        static let adminPasswordRequired = "Admin password reset value must not be empty."
        static let adminPasswordNewline = "Admin password reset value must not contain newlines."
        static func commandFailed(exitCode: Int32) -> String {
            "Command failed with exit code \(exitCode)"
        }
    }

    enum Paths {
        static let vmHome = "/Library/Application Support/TiroshVitalServer/vm"
        static let launcher = "/usr/local/bin/vitalserver-vm"
        static let uninstaller = "/usr/local/bin/tirosh-vitalserver-uninstall"
        static let vmIPFile = "/Library/Application Support/TiroshVitalServer/vm/data/run/vm-ip"
        static let runtimeState = "/Library/Application Support/TiroshVitalServer/vm/data/run/runtime-state.json"
        static let runtimeStatus = "/Library/Application Support/TiroshVitalServer/status/runtime-status.json"
        static let installLog = "/Library/Application Support/TiroshVitalServer/logs/install.log"
        static let runtimeLogs = "/Library/Application Support/TiroshVitalServer/vm/logs"
        static let backups = "/Library/Application Support/TiroshVitalServer/backups"
        static let vmConfig = "/Library/Application Support/TiroshVitalServer/vm/runtime/vm-config.json"
        static let vmDisk = "/Library/Application Support/TiroshVitalServer/vm/runtime/vm-disk.img"
        static let guestRuntimeConfig = "/Library/Application Support/TiroshVitalServer/vm/data/deploy/runtime-config.json"
        static let proxyNginxPid = "/Library/Application Support/TiroshVitalServer/nginx/logs/nginx.pid"
        static let proxyLaunchDaemon = "/Library/LaunchDaemons/com.tirosh.vitalserver-proxy.plist"
        static let commandLogFile = "/private/tmp/tirosh-vitalserver-manager-command.log"
    }

    enum Launchd {
        static let vmService = "com.tirosh.vitalserver-vm"
        static let proxyService = "com.tirosh.vitalserver-proxy"
        static let watchdogService = "com.tirosh.vitalserver-watchdog"
    }

    enum Commands {
        static let osascript = "/usr/bin/osascript"
        static let env = "/usr/bin/env"
        static let curl = "/usr/bin/curl"
        static let launchctl = "/bin/launchctl"
        static let lsof = "/usr/sbin/lsof"
    }
}
