import Foundation

public enum RuntimeControlAPIEndpoint: String, CaseIterable, Codable, Equatable, Sendable {
    case platformCapabilities
    case runtimeCapabilities
    case platformState
    case platformStateStream
    case operationState
    case platformWorkflow
    case events
    case vitalDBObservation
    case vitalDBObservationStream
    case vitalDBRecorders
    case vitalDBRecorder
    case vitalDBRecorderActivity
    case vitalDBRecorderVitalFiles
    case vitalDBBeds
    case vitalDBBed
    case vitalDBRelationships
    case hideVitalDBRecorders
    case unhideVitalDBRecorders
    case deleteVitalDBRecorders
    case hideVitalDBBeds
    case unhideVitalDBBeds
    case deleteVitalDBBeds
    case health
    case platformSettings
    case applyPlatformSettings
    case settings
    case applySettings
    case applyAdminPassword
    case release
    case installInfo
    case labScenarios
    case labVitalFiles
    case labBeds
    case createLabBeds
    case deleteLabBeds
    case resetLabBeds
    case labRecorders
    case createLabRecorders
    case deleteLabRecorders
    case resetLabRecorders
    case createLabSession
    case labSessions
    case labSession
    case startLabSession
    case stopLabSession
    case finishLabSession
    case startLabRecorder
    case stopLabRecorder
    case replayLabVitalFile
    case uploadLabVitalFile
    case guestStackStatus
    case guestServices
    case guestServiceStatus
    case guestServiceResource
    case redisRelayStatus
    case redisRelaySettings
    case applyRedisRelaySettings
    case startGuestService
    case stopGuestService
    case restartGuestService
    case repairRuntimeServices
    case repairProxy
    case repairDatastore
    case repairVMDisk
    case createRedisBackup
    case createRuntimeDataBackup
    case uninstall
    case backups
    case redisBackups
    case runtimeDataBackups
    case restoreRedisBackup
    case restoreRuntimeDataBackup
    case logText
    case logStream
    case updateBundleSummary
    case verifyUpdateBundle
    case applyUpdateBundle
    case rollbackRelease
    case rollbackBackup
    case deleteBackup
    case deleteUpdateBackup
    case deleteRuntimeDataBackup
    case exportLogs
    case createSupportExport
    case acquireOperationLease
    case heartbeatOperationLease
    case releaseOperationLease
    case guestAddress
    case putGuestAddress
    case vmLifecycle
    case putVMLifecycle
    case startRuntimeProvider
    case stopRuntimeProvider
    case restartRuntimeProvider
}
