public extension RuntimeControlAPIEndpoint {
    var streamCapability: RuntimeControlAPIStreamCapability {
        switch self {
        case .overviewStream,
             .statusStream,
             .eventStream,
             .vitalDBObservationStream,
             .logStream:
            return .supported
        case .capabilities,
             .overview,
             .status,
             .events,
             .vitalDBObservation,
             .vitalDBRecorders,
             .vitalDBRecorder,
             .vitalDBRecorderActivity,
             .vitalDBBeds,
             .vitalDBBed,
             .vitalDBRelationships,
             .health,
             .settings,
             .applySettings,
             .release,
             .installInfo,
             .startServices,
             .stopServices,
             .startTestKitService,
             .stopTestKitService,
             .restartTestKitService,
             .repairRuntimeServices,
             .repairProxy,
             .repairDatastore,
             .repairVMDisk,
             .createRedisBackup,
             .createRuntimeDataBackup,
             .uninstall,
             .backups,
             .redisBackups,
             .runtimeDataBackups,
             .restoreRedisBackup,
             .restoreRuntimeDataBackup,
             .logText,
             .updateBundleSummary,
             .verifyUpdateBundle,
             .applyUpdateBundle,
             .rollbackBackup,
             .deleteBackup,
             .deleteUpdateBackup,
             .deleteRuntimeDataBackup,
             .exportLogs:
            return .unsupported
        }
    }

    var clientAccess: RuntimeControlAPIClientAccess {
        switch self {
        case .capabilities,
             .overview,
             .overviewStream,
             .status,
             .statusStream,
             .events,
             .eventStream,
             .vitalDBObservation,
             .vitalDBObservationStream,
             .vitalDBRecorders,
             .vitalDBRecorder,
             .vitalDBRecorderActivity,
             .vitalDBBeds,
             .vitalDBBed,
             .vitalDBRelationships,
             .health,
             .settings,
             .release,
             .installInfo:
            return .browserSafe
        case .exportLogs:
            return .nativeShellOnly
        case .applySettings,
             .startServices,
             .stopServices,
             .startTestKitService,
             .stopTestKitService,
             .restartTestKitService,
             .repairRuntimeServices,
             .repairProxy,
             .repairDatastore,
             .repairVMDisk,
             .createRedisBackup,
             .createRuntimeDataBackup,
             .uninstall,
             .backups,
             .redisBackups,
             .runtimeDataBackups,
             .restoreRedisBackup,
             .restoreRuntimeDataBackup,
             .logText,
             .logStream,
             .updateBundleSummary,
             .verifyUpdateBundle,
             .applyUpdateBundle,
             .rollbackBackup,
             .deleteBackup,
             .deleteUpdateBackup,
             .deleteRuntimeDataBackup:
            return .localServerMediated
        }
    }
}
