public extension RuntimeControlAPIEndpoint {
    var streamCapability: RuntimeControlAPIStreamCapability {
        switch self {
        case .overviewStream,
             .statusStream,
             .eventStream,
             .vitalDBObservationStream,
             .logStream:
            return .supported
        case .capabilities,
             .overview,
             .status,
             .events,
             .vitalDBObservation,
             .vitalDBRecorders,
             .vitalDBRecorder,
             .vitalDBRecorderActivity,
             .vitalDBBeds,
             .vitalDBBed,
             .vitalDBRelationships,
             .hideVitalDBRecorders,
             .unhideVitalDBRecorders,
             .deleteVitalDBRecorders,
             .hideVitalDBBeds,
             .unhideVitalDBBeds,
             .deleteVitalDBBeds,
             .health,
             .settings,
             .applySettings,
             .release,
             .installInfo,
             .labScenarios,
             .labVitalFiles,
             .labBeds,
             .createLabBeds,
             .deleteLabBeds,
             .resetLabBeds,
             .labRecorders,
             .createLabRecorders,
             .deleteLabRecorders,
             .resetLabRecorders,
             .createLabSession,
             .labSession,
             .startLabSession,
             .stopLabSession,
             .replayLabVitalFile,
             .uploadLabVitalFile,
             .guestStackStatus,
             .guestServices,
             .guestServiceStatus,
             .startGuestService,
             .stopGuestService,
             .restartGuestService,
             .repairRuntimeServices,
             .repairProxy,
             .repairDatastore,
             .repairVMDisk,
             .createRedisBackup,
             .createRuntimeDataBackup,
             .uninstall,
             .backups,
             .redisBackups,
             .runtimeDataBackups,
             .restoreRedisBackup,
             .restoreRuntimeDataBackup,
             .logText,
             .updateBundleSummary,
             .verifyUpdateBundle,
             .applyUpdateBundle,
             .rollbackBackup,
             .deleteBackup,
             .deleteUpdateBackup,
             .deleteRuntimeDataBackup,
             .exportLogs:
            return .unsupported
        }
    }

    var clientAccess: RuntimeControlAPIClientAccess {
        switch self {
        case .capabilities,
             .overview,
             .overviewStream,
             .status,
             .statusStream,
             .events,
             .eventStream,
             .vitalDBObservation,
             .vitalDBObservationStream,
             .vitalDBRecorders,
             .vitalDBRecorder,
             .vitalDBRecorderActivity,
             .vitalDBBeds,
             .vitalDBBed,
             .vitalDBRelationships,
             .health,
             .settings,
             .release,
             .installInfo,
             .labScenarios,
             .labVitalFiles,
             .labBeds,
             .labRecorders,
             .labSession,
             .guestStackStatus,
             .guestServices,
             .guestServiceStatus:
            return .browserSafe
        case .exportLogs:
            return .nativeShellOnly
        case .applySettings,
             .createLabBeds,
             .deleteLabBeds,
             .resetLabBeds,
             .createLabRecorders,
             .deleteLabRecorders,
             .resetLabRecorders,
             .hideVitalDBRecorders,
             .unhideVitalDBRecorders,
             .deleteVitalDBRecorders,
             .hideVitalDBBeds,
             .unhideVitalDBBeds,
             .deleteVitalDBBeds,
             .createLabSession,
             .startLabSession,
             .stopLabSession,
             .replayLabVitalFile,
             .uploadLabVitalFile,
             .startGuestService,
             .stopGuestService,
             .restartGuestService,
             .repairRuntimeServices,
             .repairProxy,
             .repairDatastore,
             .repairVMDisk,
             .createRedisBackup,
             .createRuntimeDataBackup,
             .uninstall,
             .backups,
             .redisBackups,
             .runtimeDataBackups,
             .restoreRedisBackup,
             .restoreRuntimeDataBackup,
             .logText,
             .logStream,
             .updateBundleSummary,
             .verifyUpdateBundle,
             .applyUpdateBundle,
             .rollbackBackup,
             .deleteBackup,
             .deleteUpdateBackup,
             .deleteRuntimeDataBackup:
            return .localServerMediated
        }
    }
}
