import Foundation

public enum RuntimeControlAPIEndpoint: String, CaseIterable, Codable, Equatable, Sendable {
    case capabilities
    case overview
    case overviewStream
    case status
    case statusStream
    case operationState
    case events
    case eventStream
    case vitalDBObservation
    case vitalDBObservationStream
    case vitalDBRecorders
    case vitalDBRecorder
    case vitalDBRecorderActivity
    case vitalDBBeds
    case vitalDBBed
    case vitalDBRelationships
    case hideVitalDBRecorders
    case unhideVitalDBRecorders
    case deleteVitalDBRecorders
    case hideVitalDBBeds
    case unhideVitalDBBeds
    case deleteVitalDBBeds
    case health
    case settings
    case applySettings
    case release
    case installInfo
    case labScenarios
    case labVitalFiles
    case labBeds
    case createLabBeds
    case deleteLabBeds
    case resetLabBeds
    case labRecorders
    case createLabRecorders
    case deleteLabRecorders
    case resetLabRecorders
    case createLabSession
    case labSession
    case startLabSession
    case stopLabSession
    case replayLabVitalFile
    case uploadLabVitalFile
    case guestStackStatus
    case guestServices
    case guestServiceStatus
    case startGuestService
    case stopGuestService
    case restartGuestService
    case repairRuntimeServices
    case repairProxy
    case repairDatastore
    case repairVMDisk
    case createRedisBackup
    case createRuntimeDataBackup
    case uninstall
    case backups
    case redisBackups
    case runtimeDataBackups
    case restoreRedisBackup
    case restoreRuntimeDataBackup
    case logText
    case logStream
    case updateBundleSummary
    case verifyUpdateBundle
    case applyUpdateBundle
    case rollbackBackup
    case deleteBackup
    case deleteUpdateBackup
    case deleteRuntimeDataBackup
    case exportLogs
}
