"""Bed identity helpers."""

from __future__ import annotations

import hashlib
from uuid import uuid4

from tirosh_vitalserver.testkit.domain.bed.models import Bed
from tirosh_vitalserver.testkit.errors import (
    BedCountInvalidError,
    BedRoomNameEmptyError,
    BedRoomNameRequiredError,
    DuplicateBedRoomNameError,
)


def bed_id_for_room(room_name: str, *, admin_user_id: str = "admin") -> str:
    """Return the bed id generated by upstream VitalServer."""

    resolved_room_name = normalize_bed_room_name(room_name)

    return hashlib.sha1(f"{admin_user_id}/{resolved_room_name}".encode()).hexdigest()


def create_bed(
    *,
    room_name: str | None = None,
    prefix: str = "testkit-bed",
    admin_user_id: str = "admin",
) -> Bed:
    """Create one fresh test bed identity."""

    resolved_room_name = (
        normalize_bed_room_name(room_name)
        if room_name is not None
        else f"{normalize_bed_room_name(prefix)}-{uuid4().hex}"
    )

    return Bed(
        room_name=resolved_room_name,
        bed_id=bed_id_for_room(resolved_room_name, admin_user_id=admin_user_id),
    )


def create_beds(
    *,
    count: int,
    prefix: str = "testkit-bed",
    admin_user_id: str = "admin",
) -> tuple[Bed, ...]:
    """Create fresh test bed identities."""

    if count < 1:
        raise BedCountInvalidError()

    return tuple(
        create_bed(prefix=prefix, admin_user_id=admin_user_id)
        for _ in range(count)
    )


def beds_for_room_names(
    room_names: tuple[str, ...],
    *,
    admin_user_id: str = "admin",
) -> tuple[Bed, ...]:
    """Create bed identities for existing room names."""

    resolved_room_names = normalize_bed_room_names(room_names)

    return tuple(
        Bed(
            room_name=room_name,
            bed_id=bed_id_for_room(room_name, admin_user_id=admin_user_id),
        )
        for room_name in resolved_room_names
    )


def normalize_bed_room_names(room_names: tuple[str, ...]) -> tuple[str, ...]:
    """Return explicit, unique bed room names."""

    if not room_names:
        raise BedRoomNameRequiredError()

    resolved_room_names = tuple(normalize_bed_room_name(name) for name in room_names)
    if len(set(resolved_room_names)) != len(resolved_room_names):
        raise DuplicateBedRoomNameError()

    return resolved_room_names


def normalize_bed_room_name(room_name: str) -> str:
    """Return one explicit bed room name."""

    resolved_room_name = room_name.strip()
    if not resolved_room_name:
        raise BedRoomNameEmptyError()

    return resolved_room_name
