"""Bed identity helpers."""

from __future__ import annotations

import hashlib
from collections.abc import Callable
from uuid import uuid4

from tirosh_vitalserver.testkit.domain.bed.models import Bed
from tirosh_vitalserver.testkit.errors import (
    BedCountInvalidError,
    BedRoomNameEmptyError,
    BedRoomNameRequiredError,
    DuplicateBedRoomNameError,
)


def bed_id_for_room(room_name: str, *, admin_user_id: str = "admin") -> str:
    """Return the bed id generated by upstream VitalServer."""

    resolved_room_name = normalize_bed_room_name(room_name)

    return hashlib.sha1(f"{admin_user_id}/{resolved_room_name}".encode()).hexdigest()


def create_bed(
    *,
    room_name: str | None = None,
    prefix: str = "testbed",
    admin_user_id: str = "admin",
    suffix_factory: Callable[[], str] | None = None,
) -> Bed:
    """Create one fresh test bed identity."""

    resolved_room_name = (
        normalize_bed_room_name(room_name)
        if room_name is not None
        else generated_bed_room_name(prefix, suffix_factory=suffix_factory)
    )

    return Bed(
        room_name=resolved_room_name,
        bed_id=bed_id_for_room(resolved_room_name, admin_user_id=admin_user_id),
    )


def create_beds(
    *,
    count: int,
    prefix: str = "testbed",
    admin_user_id: str = "admin",
    reserved_room_names: tuple[str, ...] = (),
    suffix_factory: Callable[[], str] | None = None,
) -> tuple[Bed, ...]:
    """Create fresh test bed identities."""

    if count < 1:
        raise BedCountInvalidError()

    reserved = (
        set(normalize_bed_room_names(reserved_room_names))
        if reserved_room_names
        else set()
    )
    created: list[Bed] = []
    while len(created) < count:
        bed = create_bed(
            prefix=prefix,
            admin_user_id=admin_user_id,
            suffix_factory=suffix_factory,
        )
        if bed.room_name in reserved:
            continue
        reserved.add(bed.room_name)
        created.append(bed)

    return tuple(created)


def beds_for_room_names(
    room_names: tuple[str, ...],
    *,
    admin_user_id: str = "admin",
) -> tuple[Bed, ...]:
    """Create bed identities for existing room names."""

    resolved_room_names = normalize_bed_room_names(room_names)

    return tuple(
        Bed(
            room_name=room_name,
            bed_id=bed_id_for_room(room_name, admin_user_id=admin_user_id),
        )
        for room_name in resolved_room_names
    )


def normalize_bed_room_names(room_names: tuple[str, ...]) -> tuple[str, ...]:
    """Return explicit, unique bed room names."""

    if not room_names:
        raise BedRoomNameRequiredError()

    resolved_room_names = tuple(normalize_bed_room_name(name) for name in room_names)
    if len(set(resolved_room_names)) != len(resolved_room_names):
        raise DuplicateBedRoomNameError()

    return resolved_room_names


def normalize_bed_room_name(room_name: str) -> str:
    """Return one explicit bed room name."""

    resolved_room_name = room_name.strip()
    if not resolved_room_name:
        raise BedRoomNameEmptyError()

    return resolved_room_name


def generated_bed_room_name(
    prefix: str,
    *,
    suffix_factory: Callable[[], str] | None = None,
) -> str:
    """Return one generated room name with a short collision-resistant suffix."""

    resolved_prefix = normalize_bed_room_name(prefix)
    suffix = normalize_bed_room_name(
        (suffix_factory or random_bed_room_suffix)()
    )

    return f"{resolved_prefix}{suffix}"


def random_bed_room_suffix() -> str:
    """Return the default four-character generated bed suffix."""

    return uuid4().hex[:4]
