import Interfaces

typealias RuntimeViewModelTestKitStartInput = Interfaces.RuntimeViewModelTestKitStartInput
typealias RuntimeViewModelTestKitStatePolicy = Interfaces.RuntimeViewModelTestKitStatePolicy
