import Interfaces

typealias RuntimeViewModelObservabilitySnapshotLoading = Interfaces.RuntimeViewModelObservabilitySnapshotLoading
typealias RuntimeViewModelRuntimeEventRefreshResult = Interfaces.RuntimeViewModelRuntimeEventRefreshResult
typealias RuntimeViewModelVitalObservabilityRefreshResult = Interfaces.RuntimeViewModelVitalObservabilityRefreshResult
typealias RuntimeViewModelObservabilityRefresher = Interfaces.RuntimeViewModelObservabilityRefresher

extension RuntimeViewModelSnapshotLoader: RuntimeViewModelObservabilitySnapshotLoading {}
