package guestbundledupstreamimageseteffectexecutorapplication

import (
	"context"
	"testing"

	"github.com/tirosh-chain/vitalserver-runtime-platform/guest-bundled-upstream-image-set-effect-executor/internal/guestbundledupstreamimageseteffectexecutordomain"
)
type fixedClock struct{}
func (fixedClock) Now() string { return "2026-07-20T00:00:00Z" }
type inspector struct{}
func (inspector) Inspect(path, sha string) (guestbundledupstreamimageseteffectexecutordomain.ReleaseArtifact, error) { return guestbundledupstreamimageseteffectexecutordomain.ReleaseArtifact{Path: path, SHA256: sha, SizeBytes: 42}, nil }
type client struct { operation guestbundledupstreamimageseteffectexecutordomain.ImageSetOperation }
func (value client) ApplyImageSetUpdate(context.Context, guestbundledupstreamimageseteffectexecutordomain.ImageSetManagerEndpoint, guestbundledupstreamimageseteffectexecutordomain.ImageSetUpdateCommand, guestbundledupstreamimageseteffectexecutordomain.ReleaseArtifact) (guestbundledupstreamimageseteffectexecutordomain.ImageSetOperation, error) { return value.operation, nil }
func TestEffectProducesC55SuccessOnlyFromMatchingC64Success(t *testing.T) { application, err := ComposeImageSetEffectApplication(inspector{}, fixedClock{}); if err != nil { t.Fatal(err) }; invocation := fixedInvocation(); configuration := fixedConfiguration(); target := guestbundledupstreamimageseteffectexecutordomain.ActiveImageSetSelection{State: "active", ImageSetID: "bundled-upstream-030"}; operation := guestbundledupstreamimageseteffectexecutordomain.ImageSetOperation{SchemaVersion: "v1", UpdateID: invocation.UpdateID, ExpectedActiveImageSet: configuration.Apply.ExpectedActiveImageSet, TargetImageSet: guestbundledupstreamimageseteffectexecutordomain.ImageSetTarget{ImageSetID: configuration.Apply.TargetImageSetID, Artifact: guestbundledupstreamimageseteffectexecutordomain.ImageSetArtifact{SHA256: invocation.ArtifactSHA256, SizeBytes: 42, MediaType: guestbundledupstreamimageseteffectexecutordomain.ImageSetArchiveMediaType}}, State: "succeeded", ActiveImageSet: &target, ObservedAt: "2026-07-20T00:00:01Z"}; receipt, err := application.ExecuteImageSetEffect(context.Background(), configuration, invocation, client{operation}); if err != nil { t.Fatal(err) }; if receipt.State != "succeeded" { t.Fatalf("receipt=%+v", receipt) } }
func fixedConfiguration() guestbundledupstreamimageseteffectexecutordomain.ImageSetEffectExecutorConfiguration { return guestbundledupstreamimageseteffectexecutordomain.ImageSetEffectExecutorConfiguration{SchemaVersion: "v1", EffectExecutorID: "guest-bundled-upstream-image-set-effect-executor-030", ImageSetManagerEndpoint: guestbundledupstreamimageseteffectexecutordomain.ImageSetManagerEndpoint{Scheme: "http", Host: "127.0.0.1", Port: 18445, Path: guestbundledupstreamimageseteffectexecutordomain.ImageSetManagerPath, RequestTimeoutMilliseconds: 1000}, Apply: guestbundledupstreamimageseteffectexecutordomain.ImageSetOperationIntent{ExpectedActiveImageSet: guestbundledupstreamimageseteffectexecutordomain.ActiveImageSetSelection{State: "active", ImageSetID: "bundled-upstream-020"}, TargetImageSetID: "bundled-upstream-030"}} }
func fixedInvocation() guestbundledupstreamimageseteffectexecutordomain.FixedProtocolInvocation { return guestbundledupstreamimageseteffectexecutordomain.FixedProtocolInvocation{ProtocolVersion: "v1", EffectExecutorID: "guest-bundled-upstream-image-set-effect-executor-030", EffectConfigurationPath: "/host/configuration.json", ReceiptPath: "/host/receipt.json", UpdateID: "update-030", Layer: "bundled-upstream", Operation: "apply", ArtifactPath: "/host/image-set.tar.gz", ArtifactSHA256: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"} }
