"""Recorder room identity helpers."""

from __future__ import annotations

import hashlib
from collections.abc import Mapping

from tirosh_vitalserver.testkit.domain.recorder.models import RecorderRoom
from tirosh_vitalserver.testkit.types.json import JsonValue


def bed_id_for_room(room_name: str, *, admin_user_id: str = "admin") -> str:
    """Return the bed id generated by upstream VitalServer."""

    return hashlib.sha1(f"{admin_user_id}/{room_name}".encode()).hexdigest()


def iter_recorder_rooms(
    payload: Mapping[str, JsonValue],
    *,
    admin_user_id: str = "admin",
) -> tuple[RecorderRoom, ...]:
    """Return room names and bed ids found in a recorder payload."""

    rooms = payload_rooms(payload)
    results: list[RecorderRoom] = []

    for payload_key, room_payload in rooms.items():
        if not isinstance(room_payload, dict):
            continue

        room_name = room_payload.get("roomname")
        if not isinstance(room_name, str) or not room_name:
            continue

        results.append(
            RecorderRoom(
                payload_key=payload_key,
                room_name=room_name,
                bed_id=bed_id_for_room(room_name, admin_user_id=admin_user_id),
            )
        )

    return tuple(results)


def payload_rooms(payload: Mapping[str, JsonValue]) -> Mapping[str, JsonValue]:
    """Return the room map from a realtime message or room map payload."""

    rooms = payload.get("rooms")

    if isinstance(rooms, dict):
        return rooms

    return payload
